services:
  frontend:
    build:
      context: .
      secrets:
        - env_file
    volumes:
      - ./.conf/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"

secrets:
  env_file:
    file: .env
